name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    services:
      hashicorp_vault:
        image: vault
        options: >-
          --hostname hashicorp_vault
          --restart on-failure:10
          --health-cmd "vault status --address http://127.0.0.1:8200"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 60s
        env:
          VAULT_DEV_ROOT_TOKEN_ID: 2852e82e-c84c-4a82-8339-61b9ec503816
          SKIP_SETCAP: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npx eslint --ignore-path .gitignore --ext .json,.ts .

      - name: Build
        run: npm run build

      - name: Test
        run: npx vitest run --coverage
        env:
          VAULT_ADDRESS: http://hashicorp_vault:8200
          VAULT_TOKEN: 2852e82e-c84c-4a82-8339-61b9ec503816

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3